In [1]:
import numpy as np # importing numpy library 
a= np.array([1,2,3,4]) # creating the numpy array
print(a) # printing the array

[1 2 3 4]


# pre defined function in numpy

In [ ]:
b= np.array([1,2,3,4,5,6]) # initializing the numpy array
print(b.mean()) # it will print the mean of the array elements
print(b.sum()) # it will print the sum of the elements in an array
print(b.std()) # it will print standard deviation

(6,)
3.5
21
1.707825127659933


In [ ]:
c= [[1,2,3],[4,5,6],[7,8,9]] # 3*3 matrix
c= np.array(c) # convering list to numpy array
print(c)
print(c.shape) # it will print the matrix size of whichtype of matrix is it

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
d= [[[1,2,3],[4,5,6],[7,8,9]],[[1,0,0],[0,1,0],[0,0,1]]] # 2D array
d= np.array(d)
print(d)
print(d.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]]
(2, 3, 3)


# Generate array

In [ ]:
z= np.zeros((3,3)) # it will generate the array of 3*3 matrix of zero
print(z)
# In output the dot(.) shows that the values are of float type

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
z= np.ones((2,3,3))# it will generate the array of 3*3 matrix of ones in 2d array 
print(z)
# In output dot(.) means that the values are of float type

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
z= np.zeros((3,3),dtype=int) # by using dtype we can change the data type 
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Create the sequence 

In [ ]:
t= np.arange(-10,10) # it will print the data from -10 to +10
print(t)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [ ]:
r= np.arange(-10,10,.75) # here it means--- print the data from -10 to +10 with the gap of .75
print(r)
print(r.shape)# here shape will print the total no. of items in an array

[-10.    -9.25  -8.5   -7.75  -7.    -6.25  -5.5   -4.75  -4.    -3.25
  -2.5   -1.75  -1.    -0.25   0.5    1.25   2.     2.75   3.5    4.25
   5.     5.75   6.5    7.25   8.     8.75   9.5 ]
(27,)


# Another function to create sequence

In [6]:
# linspace()

q= np.linspace(10,30,30,dtype=int) # here it will print the no. from 10 to 30 and no. should be 30 in array. 
                        #here we didn't need to specify the gap it will automatically adjust the gap
print(q)
print(q.shape)

[10 10 11 12 12 13 14 14 15 16 16 17 18 18 19 20 21 21 22 23 23 24 25 25
 26 27 27 28 29 30]
(30,)


In [8]:
# logsapce()

p = np.logspace(-10,10,30)# here it will print the no. from -10 to +10 and no. should be 30 in array. 
                          #here we didn't need to apecify the gap it will automatically adjust the gap
print(p)
print(p.shape)

[1.00000000e-10 4.89390092e-10 2.39502662e-09 1.17210230e-08
 5.73615251e-08 2.80721620e-07 1.37382380e-06 6.72335754e-06
 3.29034456e-05 1.61026203e-04 7.88046282e-04 3.85662042e-03
 1.88739182e-02 9.23670857e-02 4.52035366e-01 2.21221629e+00
 1.08263673e+01 5.29831691e+01 2.59294380e+02 1.26896100e+03
 6.21016942e+03 3.03919538e+04 1.48735211e+05 7.27895384e+05
 3.56224789e+06 1.74332882e+07 8.53167852e+07 4.17531894e+08
 2.04335972e+09 1.00000000e+10]
(30,)


# Random Data

In [11]:
h = np.random.random((3,3,3)) # it will print the random value in 3*3 matrix in 3d array
print(h)

[[[0.23105966 0.06520231 0.60342832]
  [0.71943965 0.13805205 0.30164159]
  [0.12959566 0.73358421 0.49861286]]

 [[0.64018578 0.33763127 0.71093765]
  [0.03396518 0.10402199 0.67721896]
  [0.55659919 0.84309841 0.48236522]]

 [[0.4163171  0.22489321 0.53018622]
  [0.99323158 0.59247793 0.04310906]
  [0.97060756 0.66068694 0.41445577]]]


In [9]:
h2 = np.random.randint(0,50,(5,5))# it will print the random value b/w 0 to 50 in 5 rows and 5 col  
print(h2)

[[ 3 19 42 30 49]
 [34 34 31 14  7]
 [ 6 40 45 41 41]
 [47  3 32 49 13]
 [38  9  8 37 13]]


Mathematical Function:

In [16]:
import numpy as np
a= np.random.randint(0,20)
b= np.random.randint(0,20)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

20
6
91
1.8571428571428572


In [ ]:
np.cross(a,b)

AxisError: axisa: axis -1 is out of bounds for array of dimension 0

In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
np.dot(a,b) # it will print dot product of a,b 

array([[ 48,  19,  21],
       [ 97,  36,  52],
       [103,  39,  57]])

In [ ]:
np.cross(a,b) # it will print cross product of a,b 

array([[  2,  -8,   4],
       [ -6,  70, -43],
       [ -2,  49, -27]])

In [ ]:
np.cumprod(a)

array([    6,    12,    12,    12,    60,   480,   480,  2400, 21600])

In [ ]:
a.mean() # mean of all elements

4.222222222222222

In [ ]:
a.mean(axis=0) # mean along the columns

array([2.66666667, 4.        , 6.        ])

In [ ]:
a.mean(axis=1) # mean along the rows

array([3.        , 4.66666667, 5.        ])

In [ ]:
np.median(a)

5.0

In [ ]:
print(np.median(a, axis=0)) # median along the columns
print(np.median(a, axis=1)) # median along the rows

[1. 5. 8.]
[2. 5. 5.]


In [ ]:
np.sin(a)

array([[-0.2794155 ,  0.90929743,  0.84147098],
       [ 0.84147098, -0.95892427,  0.98935825],
       [ 0.84147098, -0.95892427,  0.41211849]])